package com.example.admin1.locationsharing.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONTACTS".
 */
public class Contacts {

    private Long id;
    private String first_name;
    private String last_name;
    private Integer contact_id;
    private String phone;
    private String photo;
    private Boolean is_modified;
    private Boolean is_contact_added;
    private Boolean is_location_requested;
    private Boolean is_location_shared;

    public Contacts() {
    }

    public Contacts(Long id) {
        this.id = id;
    }

    public Contacts(Long id, String first_name, String last_name, Integer contact_id, String phone, String photo, Boolean is_modified, Boolean is_contact_added, Boolean is_location_requested, Boolean is_location_shared) {
        this.id = id;
        this.first_name = first_name;
        this.last_name = last_name;
        this.contact_id = contact_id;
        this.phone = phone;
        this.photo = photo;
        this.is_modified = is_modified;
        this.is_contact_added = is_contact_added;
        this.is_location_requested = is_location_requested;
        this.is_location_shared = is_location_shared;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirst_name() {
        return first_name;
    }

    public void setFirst_name(String first_name) {
        this.first_name = first_name;
    }

    public String getLast_name() {
        return last_name;
    }

    public void setLast_name(String last_name) {
        this.last_name = last_name;
    }

    public Integer getContact_id() {
        return contact_id;
    }

    public void setContact_id(Integer contact_id) {
        this.contact_id = contact_id;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public Boolean getIs_modified() {
        return is_modified;
    }

    public void setIs_modified(Boolean is_modified) {
        this.is_modified = is_modified;
    }

    public Boolean getIs_contact_added() {
        return is_contact_added;
    }

    public void setIs_contact_added(Boolean is_contact_added) {
        this.is_contact_added = is_contact_added;
    }

    public Boolean getIs_location_requested() {
        return is_location_requested;
    }

    public void setIs_location_requested(Boolean is_location_requested) {
        this.is_location_requested = is_location_requested;
    }

    public Boolean getIs_location_shared() {
        return is_location_shared;
    }

    public void setIs_location_shared(Boolean is_location_shared) {
        this.is_location_shared = is_location_shared;
    }

}
