package com.example.admin1.locationsharing.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.admin1.locationsharing.db.dao.SharedContactTable;
import com.example.admin1.locationsharing.db.dao.UserLastKnownLocation;
import com.example.admin1.locationsharing.db.dao.UserLocations;

import com.example.admin1.locationsharing.db.dao.SharedContactTableDao;
import com.example.admin1.locationsharing.db.dao.UserLastKnownLocationDao;
import com.example.admin1.locationsharing.db.dao.UserLocationsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sharedContactTableDaoConfig;
    private final DaoConfig userLastKnownLocationDaoConfig;
    private final DaoConfig userLocationsDaoConfig;

    private final SharedContactTableDao sharedContactTableDao;
    private final UserLastKnownLocationDao userLastKnownLocationDao;
    private final UserLocationsDao userLocationsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sharedContactTableDaoConfig = daoConfigMap.get(SharedContactTableDao.class).clone();
        sharedContactTableDaoConfig.initIdentityScope(type);

        userLastKnownLocationDaoConfig = daoConfigMap.get(UserLastKnownLocationDao.class).clone();
        userLastKnownLocationDaoConfig.initIdentityScope(type);

        userLocationsDaoConfig = daoConfigMap.get(UserLocationsDao.class).clone();
        userLocationsDaoConfig.initIdentityScope(type);

        sharedContactTableDao = new SharedContactTableDao(sharedContactTableDaoConfig, this);
        userLastKnownLocationDao = new UserLastKnownLocationDao(userLastKnownLocationDaoConfig, this);
        userLocationsDao = new UserLocationsDao(userLocationsDaoConfig, this);

        registerDao(SharedContactTable.class, sharedContactTableDao);
        registerDao(UserLastKnownLocation.class, userLastKnownLocationDao);
        registerDao(UserLocations.class, userLocationsDao);
    }
    
    public void clear() {
        sharedContactTableDaoConfig.getIdentityScope().clear();
        userLastKnownLocationDaoConfig.getIdentityScope().clear();
        userLocationsDaoConfig.getIdentityScope().clear();
    }

    public SharedContactTableDao getSharedContactTableDao() {
        return sharedContactTableDao;
    }

    public UserLastKnownLocationDao getUserLastKnownLocationDao() {
        return userLastKnownLocationDao;
    }

    public UserLocationsDao getUserLocationsDao() {
        return userLocationsDao;
    }

}
