package com.example.admin1.locationsharing.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.admin1.locationsharing.db.dao.SharedContactTable;

import com.example.admin1.locationsharing.db.dao.SharedContactTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sharedContactTableDaoConfig;

    private final SharedContactTableDao sharedContactTableDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sharedContactTableDaoConfig = daoConfigMap.get(SharedContactTableDao.class).clone();
        sharedContactTableDaoConfig.initIdentityScope(type);

        sharedContactTableDao = new SharedContactTableDao(sharedContactTableDaoConfig, this);

        registerDao(SharedContactTable.class, sharedContactTableDao);
    }
    
    public void clear() {
        sharedContactTableDaoConfig.getIdentityScope().clear();
    }

    public SharedContactTableDao getSharedContactTableDao() {
        return sharedContactTableDao;
    }

}
