package com.example.admin1.locationsharing.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_LOCATIONS".
 */
public class UserLocations {

    private Long id;
    private String token;
    private String latitude;
    private String longitude;
    private String radius;
    private String time;

    public UserLocations() {
    }

    public UserLocations(Long id) {
        this.id = id;
    }

    public UserLocations(Long id, String token, String latitude, String longitude, String radius, String time) {
        this.id = id;
        this.token = token;
        this.latitude = latitude;
        this.longitude = longitude;
        this.radius = radius;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getRadius() {
        return radius;
    }

    public void setRadius(String radius) {
        this.radius = radius;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

}
