package com.example.admin1.locationsharing.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_LAST_KNOWN_LOCATION".
 */
public class UserLastKnownLocation {

    private String name;
    private String phone;
    private String latitude;
    private String longitude;

    public UserLastKnownLocation() {
    }

    public UserLastKnownLocation(String phone) {
        this.phone = phone;
    }

    public UserLastKnownLocation(String name, String phone, String latitude, String longitude) {
        this.name = name;
        this.phone = phone;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

}
