package com.example.admin1.locationsharing.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_LAST_KNOWN_LOCATION".
 */
public class UserLastKnownLocation {

    private Long id;
    private String name;
    private String token;
    private String latitude;
    private String longitude;
    private String time;

    public UserLastKnownLocation() {
    }

    public UserLastKnownLocation(Long id) {
        this.id = id;
    }

    public UserLastKnownLocation(Long id, String name, String token, String latitude, String longitude, String time) {
        this.id = id;
        this.name = name;
        this.token = token;
        this.latitude = latitude;
        this.longitude = longitude;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

}
