package com.riktam.mapmate.locationsharing.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.riktam.mapmate.locationsharing.db.dao.UserLocations;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_LOCATIONS".
*/
public class UserLocationsDao extends AbstractDao<UserLocations, Long> {

    public static final String TABLENAME = "USER_LOCATIONS";

    /**
     * Properties of entity UserLocations.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Email = new Property(1, String.class, "email", false, "EMAIL");
        public final static Property Latitude = new Property(2, String.class, "latitude", false, "LATITUDE");
        public final static Property Longitude = new Property(3, String.class, "longitude", false, "LONGITUDE");
        public final static Property Radius = new Property(4, String.class, "radius", false, "RADIUS");
        public final static Property Created_time = new Property(5, String.class, "created_time", false, "CREATED_TIME");
        public final static Property Updated_time = new Property(6, String.class, "updated_time", false, "UPDATED_TIME");
        public final static Property Sharing = new Property(7, Integer.class, "sharing", false, "SHARING");
    };


    public UserLocationsDao(DaoConfig config) {
        super(config);
    }
    
    public UserLocationsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_LOCATIONS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"EMAIL\" TEXT," + // 1: email
                "\"LATITUDE\" TEXT," + // 2: latitude
                "\"LONGITUDE\" TEXT," + // 3: longitude
                "\"RADIUS\" TEXT," + // 4: radius
                "\"CREATED_TIME\" TEXT," + // 5: created_time
                "\"UPDATED_TIME\" TEXT," + // 6: updated_time
                "\"SHARING\" INTEGER);"); // 7: sharing
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_LOCATIONS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UserLocations entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(2, email);
        }
 
        String latitude = entity.getLatitude();
        if (latitude != null) {
            stmt.bindString(3, latitude);
        }
 
        String longitude = entity.getLongitude();
        if (longitude != null) {
            stmt.bindString(4, longitude);
        }
 
        String radius = entity.getRadius();
        if (radius != null) {
            stmt.bindString(5, radius);
        }
 
        String created_time = entity.getCreated_time();
        if (created_time != null) {
            stmt.bindString(6, created_time);
        }
 
        String updated_time = entity.getUpdated_time();
        if (updated_time != null) {
            stmt.bindString(7, updated_time);
        }
 
        Integer sharing = entity.getSharing();
        if (sharing != null) {
            stmt.bindLong(8, sharing);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public UserLocations readEntity(Cursor cursor, int offset) {
        UserLocations entity = new UserLocations( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // email
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // latitude
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // longitude
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // radius
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // created_time
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // updated_time
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7) // sharing
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UserLocations entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEmail(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLatitude(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLongitude(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRadius(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCreated_time(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setUpdated_time(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSharing(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(UserLocations entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(UserLocations entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
