package com.riktam.mapmate.locationsharing.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_LAST_KNOWN_LOCATION".
 */
public class UserLastKnownLocation {

    private Long id;
    private String friend_first_name;
    private String email;
    private Integer sharing;
    private String last_known_time;
    private String latitude;
    private String longitude;
    private String time;
    private String friend_profile;

    public UserLastKnownLocation() {
    }

    public UserLastKnownLocation(Long id) {
        this.id = id;
    }

    public UserLastKnownLocation(Long id, String friend_first_name, String email, Integer sharing, String last_known_time, String latitude, String longitude, String time, String friend_profile) {
        this.id = id;
        this.friend_first_name = friend_first_name;
        this.email = email;
        this.sharing = sharing;
        this.last_known_time = last_known_time;
        this.latitude = latitude;
        this.longitude = longitude;
        this.time = time;
        this.friend_profile = friend_profile;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFriend_first_name() {
        return friend_first_name;
    }

    public void setFriend_first_name(String friend_first_name) {
        this.friend_first_name = friend_first_name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Integer getSharing() {
        return sharing;
    }

    public void setSharing(Integer sharing) {
        this.sharing = sharing;
    }

    public String getLast_known_time() {
        return last_known_time;
    }

    public void setLast_known_time(String last_known_time) {
        this.last_known_time = last_known_time;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getFriend_profile() {
        return friend_profile;
    }

    public void setFriend_profile(String friend_profile) {
        this.friend_profile = friend_profile;
    }

}
