package com.riktam.mapmate.locationsharing.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_GMAIL_FRIENDS".
 */
public class UserGmailFriends {

    private Long id;
    private String name;
    private String email;
    private String profilePicUrl;

    public UserGmailFriends() {
    }

    public UserGmailFriends(Long id) {
        this.id = id;
    }

    public UserGmailFriends(Long id, String name, String email, String profilePicUrl) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.profilePicUrl = profilePicUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getProfilePicUrl() {
        return profilePicUrl;
    }

    public void setProfilePicUrl(String profilePicUrl) {
        this.profilePicUrl = profilePicUrl;
    }

}
